ls:
  src/*/{src,__tests__}:
    .dir: kebab-case
    .js: kebab-case
    .jsx: PascalCase
    .ts: camelCase
    .tsx: PascalCase
    .d.ts: kebab-case
    .mock.ts: kebab-case
    .test-d.ts: kebab-case
    .config.js: kebab-case
    .umd.js: kebab-case
    .spec.ts: camelCase
    .spec.ts.snap: camelCase
    .stories.js: PascalCase
    .stories.ts: PascalCase
    .stories.mdx: kebab-case
    .vue: PascalCase
